categories:
- title: ⚠ Breaking Changes
  labels:
  - breaking
- title: 🐜 Bug Fixes
  labels:
  - bug
- title: 📏 Evaluation Support
  labels:
  - evaluation
  - batch
- title: 🧩 Algorithms
  labels:
  - algorithms
- title: 🧱 Internals
  labels:
  - internals
- title: 🔧 Maintenance
  labels:
  - build
  - dependencies
template: |
  ## What’s Changed

  $CHANGES
