# Changes here will be overwritten by Copier
_commit: 28184e6
_src_path: https://github.com/lenskit/lk-project-template
package_name: lenskit
project_name: lenskit
require_lint: true
start_year: 2018
