# Changes here will be overwritten by Copier
_commit: d7a66f4
_src_path: https://github.com/lenskit/lk-project-template
owner: Drexel University and contributors
package_name: lenskit
project_descr: Toolkit for recommender systems research, teaching, and more.
project_name: lenskit
project_title: LensKit
require_lint: false
start_year: 2018
typecheck: false
