header:
  license:
    spdx-id: MIT
    copyright-owner: Drexel University and collaborators
    content: |
      This file is part of LensKit.
      Copyright (C) 2018-2023 Boise State University.
      Copyright (C) 2023-2025 Drexel University.
      Licensed under the MIT license, see LICENSE.md for details.
      SPDX-License-Identifier: MIT

    pattern: |
      This file is part of LensKit.
      Copyright (C) \d+-2023 Boise State University\.?
      Copyright (C) 2023-\d+ Drexel University\.?
      Licensed under the MIT license, see LICENSE.md for details.
      SPDX-License-Identifier: MIT

  paths:
    - tasks.py
    - src/**/*.py

  paths-ignore:
    - "dist"
    - "build"
    - ".venv"
    - ".pixi"
    - "output"
    - "licenses"
    - "**/*.md"
    - "LICENSE.md"

  comment: on-failure

dependency:
  files:
    - Cargo.toml
