version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "mambaforge-latest"

sphinx:
  configuration: docs/conf.py

conda:
  environment: docs/environment.yml

python:
  install:
    - method: pip
      path: lenskit
    - method: pip
      path: lenskit-funksvd
    - method: pip
      path: lenskit-implicit
    - method: pip
      path: lenskit-hpf
