# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/vsts/pipelines/languages/python
variables:
  conda.deps: >
    python=$(python.version)
    pandas scipy pytables fastparquet python-snappy numba
    invoke coverage pytest-cov
  pip.deps: >
    invoke pytest coverage pytest-cov
    pandas scipy pyarrow
    numba

jobs:

- job: 'LinuxConda'
  pool:
    vmImage: ubuntu-16.04
  strategy:
    matrix:
      Python35:
        python.version: '3.5'
      Python36:
        python.version: '3.6'
      Python37:
        python.version: '3.7'
    maxParallel: 4

  steps:
  - task: CondaEnvironment@1
    inputs:
      createCustomEnvironment: true
      environmentName: lkpy
      packageSpecs: $(conda.deps)
      updateConda: false
    
  - script: |
      sudo pip install pytest pytest-arraydiff
    displayName: current pytest

  - script: |
      if [ ! -r ~/ml-100k/u.data ]; then
        wget --no-verbose -O ml-100k.zip http://files.grouplens.org/datasets/movielens/ml-100k.zip
        unzip -d ~ ml-100k.zip
      fi
    displayName: 'Download ML-100K'

  - script: |
      python3 setup.py build
    displayName: 'Build LKPY'

  - script: |
      python3 setup.py test
    displayName: 'Test LKPY'

  - script: |
      env NUMBA_DISABLE_JIT=1 invoke test --cover --no-eval --no-slow --verbose
    displayName: 'Test Coverage'

  - script: |
      coverage xml
      echo "Fetching Codecov script"
      curl -o /tmp/codecov.sh https://codecov.io/bash
      
      echo "Building for $BUILD_REASON"
      cc_args=
      if [ -n "$SYSTEM_PULLREQUEST_PULLREQUESTNUMBER" ]; then
        ccargs="-P $SYSTEM_PULLREQUEST_PULLREQUESTNUMBER"
      fi
      if [ -z "$CODECOV_TOKEN" ]; then
        echo "no CODECOV_TOKEN :(" >&2
      fi

      bash /tmp/codecov.sh -C "$BUILD_SOURCEVERSION" -B $BUILD_SOURCEBRANCH $cc_args
    displayName: 'Upload Coverage'

- job: 'LinuxVanilla'
  pool:
    vmImage: ubuntu-16.04
  strategy:
    matrix:
      Python35:
        python.version: '3.5'
      Python36:
        python.version: '3.6'
      Python37:
        python.version: '3.7'
    maxParallel: 4

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'
      architecture: 'x64'

  - script: |
      python -m pip install --upgrade pip
      pip install $(pip.deps)
    displayName: 'Install dependencies'

  - script: |
      if [ ! -r ~/ml-100k/u.data ]; then
        wget --no-verbose -O ml-100k.zip http://files.grouplens.org/datasets/movielens/ml-100k.zip
        unzip -d ~ ml-100k.zip
      fi
    displayName: 'Download ML-100K'
    
  - script: |
      python3 setup.py test
    displayName: 'pytest'
  
  - script: |
      env NUMBA_DISABLE_JIT=1 invoke test --cover --no-eval --no-slow --verbose
    displayName: 'Test Coverage'

  - script: |
      coverage xml
      echo "Fetching Codecov script"
      curl -o /tmp/codecov.sh https://codecov.io/bash
      
      echo "Building for $BUILD_REASON"
      cc_args=
      if [ -n "$SYSTEM_PULLREQUEST_PULLREQUESTNUMBER" ]; then
        ccargs="-P $SYSTEM_PULLREQUEST_PULLREQUESTNUMBER"
      fi
      if [ -z "$CODECOV_TOKEN" ]; then
        echo "no CODECOV_TOKEN :(" >&2
      fi

      bash /tmp/codecov.sh -C "$BUILD_SOURCEVERSION" -B $BUILD_SOURCEBRANCH $cc_args
    displayName: 'Upload Coverage'

- job: 'WindowsVanilla'
  pool:
    vmImage: vs2017-win2016
  
  steps:
  - script: |
      python -m pip install --upgrade pip
      pip install $(pip.deps)
    displayName: 'Install dependencies'

  - script: |
      python setup.py test
    displayName: 'pytest'

- job: 'WindowsConda'
  pool:
    vmImage: vs2017-win2016
  strategy:
    matrix:
      Python35:
        python.version: '3.5'
      Python36:
        python.version: '3.6'
      # Python37:
      #   python.version: '3.7'
    maxParallel: 4

  steps:
  - task: CondaEnvironment@1
    inputs:
      createCustomEnvironment: true
      environmentName: lkpy
      packageSpecs: $(conda.deps)

  - script: |
      sudo pip install pytest pytest-arraydiff
    displayName: current pytest

  - script: |
      python -V
      python setup.py build
    displayName: 'Build LKPY'

  - script: |
      python -V
      python setup.py test
    displayName: 'Test LKPY'

- job: 'MacConda'
  pool:
    vmImage: 'macOS-10.13'
  strategy:
    matrix:
      Python35:
        python.version: '3.5'
      Python36:
        python.version: '3.6'
      Python37:
        python.version: '3.7'
    maxParallel: 4

  steps:
  - task: CondaEnvironment@1
    inputs:
      createCustomEnvironment: true
      environmentName: lkpy
      packageSpecs: $(conda.deps)
      updateConda: false

  - script: |
      sudo pip install pytest pytest-arraydiff
    displayName: current pytest

  - script: |
      if [ ! -r ~/ml-100k/u.data ]; then
        wget --no-verbose -O ml-100k.zip http://files.grouplens.org/datasets/movielens/ml-100k.zip
        unzip -d ~ ml-100k.zip
      fi
    displayName: 'Download ML-100K'
    
  - script: |
      python3 setup.py build
    displayName: 'Build LKPY'

  - script: |
      python3 setup.py test
    displayName: 'Test LKPY'
