name: lkpy-old
channels:
  - mdekstrand
  - defaults
dependencies:
- python=3.6
- pip
- pandas=0.24
- numpy=1.16
- scipy
- python-snappy
- numba=0.43
- mkl-devel
- c-compiler
- cffi
- pyarrow
- joblib
- coverage 
- pytest>=3.9
- pytest-cov
- pytest-doctestplus
- ipython
- flake8
