[project]
name = "lenskit"
channels = ["conda-forge", "pytorch", "nodefaults"]
platforms = ["linux-64", "win-64", "osx-arm64"]

[dependencies]
pandas = ">=1.5, <3"
numpy = ">=1.23, <2"
scipy = ">=1.9"
pytorch = "~=2.1"
threadpoolctl = ">=3.0"
pydantic = ">=2.8,<3"
structlog = ">=24.4.0,<25"

[pypi-dependencies]
manylog = { git = "https://github.com/mdekstrand/manylog.git" }
lenskit = { path = "lenskit", editable = true }

[feature.py311.dependencies]
python = "=3.11"

[feature.py312.dependencies]
python = "=3.12"

[feature.sklearn.dependencies]
scikit-learn = "~=1.1"

[feature.sklearn.pypi-dependencies]
lenskit-sklearn = { path = "lenskit-sklearn", editable = true }

[feature.funksvd.dependencies]
numba = ">=0.56"

[feature.funksvd.pypi-dependencies]
lenskit-funksvd = { path = "lenskit-funksvd", editable = true }

[feature.implicit]
platforms = ["linux-64", "osx-arm64"]

[feature.implicit.dependencies]
implicit = ">=0.6.1"

[feature.implicit.pypi-dependencies]
lenskit-implicit = { path = "lenskit-implicit", editable = true }

[feature.hpf]
platforms = ["linux-64", "osx-arm64"]

[feature.hpf.dependencies]
hpfrec = "~=0.2.0"

[feature.hpf.pypi-dependencies]
lenskit-hpf = { path = "lenskit-hpf", editable = true }

[feature.test.dependencies]
pytest = "~=8.2"
pytest-doctestplus = ">=1.2.1,<2"
pytest-cov = ">=2.12"
pytest-benchmark = "=4"
pytest-repeat = ">=0.9"
hypothesis = ">=6.16"
pyprojroot = "=0.3"

[feature.doc.dependencies]
sphinx = ">=4.2"
sphinxext-opengraph = ">=0.5"
sphinxcontrib-bibtex = ">=2.0"
pydata-sphinx-theme = "~=0.16.0"
myst-nb = ">=0.13"
just = ">=1.2"
sphinx-togglebutton = ">=0.3.2,<0.4"
sphinxcontrib-mermaid = ">=1.0.0,<2"

[feature.dev.dependencies]
hatchling = "~=1.24"
hatch-vcs = "~=0.4.0"
python-build = "~=1.0"
ruff = ">=0.2"
pyright = ">=1.1"
pre-commit = ">=3.7"
copier = "~=9.0"
ipython = ">=7"
pyarrow = ">=15"
sphinx-autobuild = ">=2021"
docopt = ">=0.6"
tomlkit = ">=0.12"
pyyaml = "~=6.0"
packaging = ">=24.0"
tqdm = ">=4"
pandas-stubs = ">=1.5,<3"
just = ">=1.2"
deno = "~=1.46"

[feature.dev.pypi-dependencies]
unbeheader = ">=1.3,<2"

[feature.demo.dependencies]
notebook = ">=6"
nbval = ">=0.9"
matplotlib = "~=3.4"
nbformat = ">=5.2"
ipython = ">=7"
pyprojroot = ">=0.3"
seaborn-base = ">=0.13.2,<0.14"
ipywidgets = ">=8.1.5,<9"

[feature.reporting.dependencies]
sqlite = "~=3.0"
diff-cover = ">=9.1"
coverage = ">=5"
tk = "~=8.6"

[environments]
doc = { features = [
  "py312",
  "doc",
  "funksvd",
  "hpf",
  "implicit",
], solve-group = "py312-nix" }
demo = { features = [
  "py312",
  "demo",
  "funksvd",
  "hpf",
  "implicit",
], solve-group = "py312-nix" }
report = { features = ["reporting"], no-default-feature = true }

dev-core = { features = ["dev", "doc", "test", "demo"] }
dev-full = { features = [
  "dev",
  "doc",
  "test",
  "demo",
  "sklearn",
  "funksvd",
  "implicit",
  "hpf",
], solve-group = "py312-nix" }
dev-compat = { features = [
  "dev",
  "doc",
  "test",
  "demo",
  "sklearn",
  "funksvd",
  "implicit",
  "hpf",
], solve-group = "py311-nix" }

test-py311-core = { features = ["py311", "test"], solve-group = "py311" }
test-py312-core = { features = ["py312", "test"], solve-group = "py312" }

test-py311-sklearn = { features = [
  "py311",
  "test",
  "sklearn",
], solve-group = "py311" }
test-py312-sklearn = { features = [
  "py312",
  "test",
  "sklearn",
], solve-group = "py312" }

test-py311-funksvd = { features = [
  "py311",
  "test",
  "funksvd",
], solve-group = "py311" }
test-py312-funksvd = { features = [
  "py312",
  "test",
  "funksvd",
], solve-group = "py312" }

test-py311-implicit = { features = [
  "py311",
  "test",
  "implicit",
], solve-group = "py311" }
test-py312-implicit = { features = [
  "py312",
  "test",
  "implicit",
], solve-group = "py312" }

test-py311-hpf = { features = [
  "py311",
  "test",
  "hpf",
], solve-group = "py311-nix" }
test-py312-hpf = { features = [
  "py312",
  "test",
  "hpf",
], solve-group = "py312-nix" }

test-py311-full = { features = [
  "py311",
  "test",
  "sklearn",
  "funksvd",
  "implicit",
  "hpf",
], solve-group = "py311-nix" }
test-py312-full = { features = [
  "py312",
  "test",
  "sklearn",
  "funksvd",
  "implicit",
  "hpf",
], solve-group = "py312-nix" }
test-examples = { features = [
  "demo",
  "test",
  "funksvd",
  "hpf",
  "implicit",
], solve-group = "py311-nix" }

[target.osx-arm64.dependencies]
# pytorch = { version = "~=2.1", channel = "pytorch" }
