[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "lenskit"
authors = [
    {name = "Michael Ekstrand", email = "michaelekstrand@boisestate.edu"}
]
classifiers = [
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Operating System :: OS Independent",
    "Intended Audience :: Science/Research",
]
readme = "README.md"
license = { file = "LICENSE.md" }
requires-python = ">= 3.8"
dynamic = ['version', 'description']
dependencies = [
    "pandas >=1.4, <2",
    "numpy >= 1.22",
    "scipy >= 1.8.0",
    "numba >= 0.56, < 0.59",
    "cffi >= 1.15.0",
    "psutil >= 5",
    "binpickle >= 0.3.2",
    "seedbank >= 0.1.0",
    "csr >= 0.5",
]

[project.urls]
homepage = "https://lenskit.org"
documentation = "https://lkpy.lenskit.org"
source = "https://github.com/lenskit/lkpy"

[project.optional-dependencies]
test = [
    "pytest ==7.*",
    "pytest-doctestplus >= 0.9",
    "coverage >= 5",
    "pytest-cov >= 2.12",
    "hypothesis >= 6"
]
dev = [
    "lenskit-build-helpers >=0.1",  # p2c: -p
    "flit >= 3",
    "pyproject2conda >=0.8",
    "invoke >=1",
    "requests >=2",
    "packaging >= 20",
    "flake8 >= 3",
    "ipython >= 7",
    "docopt >= 0.6",
    "tqdm >= 4",
    "keyring",
    "sphinx-autobuild >= 2021",
]
doc = [
    "sphinx >= 4.2",
    "sphinxcontrib-bibtex >= 2.0",
    "sphinx_rtd_theme >= 0.5",
    "myst-nb >= 0.13",
]
demo = [
    "notebook >= 6",
    "nbval >= 0.9",
    "matplotlib ~= 3.4",
    "nbformat >=5.2",
    "ipython >= 7",
]
sklearn = ["scikit-learn >= 1.1"]

[tool.flit.sdist]
exclude = [
    ".github",
    "*.ipynb",
    "docs",
    "data",
    "examples",
    "build-tools",
    "lkbuild",
    "tasks.py",
    "tests",
]

[tool.pyproject2conda]
channels = ["conda-forge"]
python = ["3.10", "3.11"]
default_envs = ["test", "sklearn", "doc", "demo"]
template_python = "envs/lenskit-py{py_version}-{env}"
template = "envs/{env}"

[tool.pyproject2conda.envs.dev]
extras = ["dev", "test", "doc", "demo", "sklearn"]

[tool.pyproject2conda.envs.ci]
extras = ["test", "sklearn"]

[tool.pyproject2conda.envs.demo-ci]
extras = ["test", "demo"]
