[build-system]
requires = ["flit_core >=2,<4"]
build-backend = "flit_core.buildapi"

[tool.flit.metadata]
module = "lenskit"
author = "Michael Ekstrand"
author-email = "michaelekstrand@boisestate.edu"
home-page = "https://lenskit.lenskit.org"
classifiers = [
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Operating System :: OS Independent",
    "Intended Audience :: Science/Research",
]
requires-python = ">= 3.7"
description-file = "README.md"
requires = [
    "pandas >= 0.24",
    "numpy >= 1.17",
    "scipy >= 1.2",
    "numba >= 0.51, < 0.54",
    "pyarrow >= 0.15",
    "cffi >= 1.12.2",
    "binpickle >= 0.3.2",
    "psutil >= 5",
    "seedbank @ git+https://github.com/lenskit/seedbank.git",
    "csr @ git+https://github.com/lenskit/csr.git",
]

[tool.flit.metadata.requires-extra]
test = [
    "pytest >= 6",
    "pytest-doctestplus >= 0.9",
    "hypothesis >= 6"
]
dev = [
    "flit",
    "packaging",
    "flake8",
    "coverage",
    "pytest-cov",
    "ipython",
    "docopt",
    "tqdm",
    "sphinx-autobuild",
]
doc = [
    "sphinx >= 3",
    "sphinx_rtd_theme",
    "nbsphinx",
    "recommonmark",
    "ipython",
]
demo = [
    "notebook >= 6",
    "nbval >= 0.9",
    "matplotlib >= 3",
]
hpf = ["hpfrec"]
implicit = ["implicit"]
sklearn = ["scikit-learn >= 0.22"]
tf = ["tensorflow >= 2.1"]

[tool.flit.sdist]
exclude = [
    ".github",
    "*.ipynb",
    "doc",
    "data",
    "examples",
    "build-tools",
    "tests",
]

[tool.envtool.conda]
name = "lkpy"
channels = [
    "conda-forge"
]

[tool.envtool.conda.overrides]
hpfrec = { source="pip" }

[tool.envtool.conda.extras]
# ".none" = [
#     "tbb"
# ]
mkl = [
    "libblas=*=*mkl"
]
openblas = [
    "libblas=*=*openblas"
]
