[build-system]
requires = ["flit_core >=2,<4"]
build-backend = "flit_core.buildapi"

[tool.flit.metadata]
module = "lenskit"
author = "Michael Ekstrand"
author-email = "michaelekstrand@boisestate.edu"
home-page = "https://lenskit.org"
classifiers = [
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Operating System :: OS Independent",
    "Intended Audience :: Science/Research",
]
requires-python = ">= 3.7"
description-file = "README.md"
requires = [
    "pandas >=1.0, ==1.*",
    "numpy >= 1.17",
    "scipy >= 1.2",
    "numba >= 0.51, < 0.55",
    "cffi >= 1.12.2",
    "psutil >= 5",
    "binpickle >= 0.3.2",
    "seedbank >= 0.1.0",
    "csr >= 0.3.1",
]

[tool.flit.metadata.urls]
Documentation = "https://lkpy.lenskit.org"
GitHub = "https://github.com/lenskit/lkpy"

[tool.flit.metadata.requires-extra]
test = [
    "pytest >= 6",
    "pytest-doctestplus >= 0.9",
    "hypothesis >= 6"
]
dev = [
    "flit >= 3",
    "conda-lock",
    "invoke >=1",
    "packaging >= 20",
    "flake8 >= 3",
    "coverage >= 5",
    "pytest-cov >= 2.12",
    "ipython >= 7",
    "docopt >= 0.6",
    "tqdm >= 4",
    "sphinx-autobuild >= 2021",
]
doc = [
    "sphinx >= 3",
    "sphinxcontrib-bibtex >= 2.0",
    "sphinx_rtd_theme >= 0.5",
    "nbsphinx >= 0.8",
]
demo = [
    "notebook >= 6",
    "nbval >= 0.9",
    "matplotlib ~= 3.4",
]
hpf = ["hpfrec"]
implicit = ["implicit"]
sklearn = ["scikit-learn >= 0.22"]
tf = ["tensorflow >=2.1,<2.6"]

[tool.flit.sdist]
exclude = [
    ".github",
    "*.ipynb",
    "doc",
    "data",
    "examples",
    "build-tools",
    "lkbuild",
    "tasks.py",
    "tests",
]

[tool.conda-lock]
channels = ['conda-forge']
