jobs:
- job: 'MinimalDeps'
  pool:
    vmImage: ubuntu-16.04

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.6'
      architecture: 'x64'

  - script: |
      # we need pip
      python -m pip install --upgrade pip wheel
      # earliest supported versions of versioned deps
      pip install pandas==0.24.* numba==0.43.*
      # install test things
      pip install pytest pytest-doctestplus coverage pytest-cov
    displayName: 'Install base versioned dependencies'

  - script: |
      python -m pip install -e .
    displayName: 'Install LensKit and dependencies'
  
  - script: |
      mkdir -p build
      python3 -m pytest --junitxml=build/test-results.xml --cov=lenskit
    displayName: 'Run tests'

  - task: PublishTestResults@2
    condition: succeededOrFailed()
    inputs:
      testResultsFiles: 'build/test-results.xml'
      testRunTitle: 'Publish test results for Python $(python.version)'
  
  - template: ./nix-coverage.yml
