name: Setup Conda Environment
description: >
  Set up a Conda environment.
inputs:
  name:
    description: Environment name
    required: true
  env-file:
    description: Environment file
    required: true
  python-version:
    description: Python version (for initializing the environment)
    required: false
runs:
  using: node12
  main: main.js
