[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "lenskit-funksvd"
description = "FunkSVD recommendation model for LensKit."
authors = [{ name = "Michael Ekstrand", email = "mdekstrand@drexel.edu" }]
classifiers = [
  "License :: OSI Approved :: MIT License",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Operating System :: OS Independent",
  "Intended Audience :: Science/Research",
]
requires-python = ">= 3.11"
readme = "README.md"
license = { file = "LICENSE.md" }
version = "2025.1.1rc1"
dependencies = ["lenskit[funksvd]>=2025.1.1b12"]

[project.urls]
homepage = "https://lenskit.org"
documentation = "https://lkpy.lenskit.org"
source = "https://github.com/lenskit/lkpy"
