# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      # use `-browsers` prefix for selenium tests, e.g. `3.6.1-browsers`
      - image: circleci/python:3.6-stretch

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "setup.py" }}

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate

      - run:
          name: run tests
          command: |
            . venv/bin/activate
            python setup.py test

      - save_cache:
          paths:
            - ./.eggs
          key: v1-dependencies-{{ checksum "setup.py" }}

      - store_artifacts:
          path: test-reports
          destination: test-reports
          