# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
dirs: &dirs
  working_directory: ~/lkpy
  environment:
    ML100K_DIR: ~/ml-100k

build_steps: &build_steps
  - attach_workspace:
      at: ~/
  - restore_cache:
      keys:
      - dep-eggs-py37-{{ checksum "setup.py" }}

  - run:
      name: initialize environment
      command: |
        python3 -m venv venv
        . venv/bin/activate

  - run:
      name: build and test
      command: |
        . venv/bin/activate
        python setup.py test

  - save_cache:
      paths:
        - ./.eggs
      key: dep-eggs-py37-{{ checksum "setup.py" }}  

version: 2
jobs:
  checkout:
    docker:
      - image: circleci/python:3.6-stretch
    <<: *dirs
    steps:
      - checkout
      - restore_cache:
          keys:
          - ml-data
      - run:
          name: fetch data set
          command: |
            if [ ! -r ~/ml-100k/u.data ]; then
              wget --no-verbose -O ml-100k.zip http://files.grouplens.org/datasets/movielens/ml-100k.zip
              unzip -d ~ ml-100k.zip
            fi
      - save_cache:
          paths:
            - ./ml-100k
          key: ml-data
      - persist_to_workspace:
          root: ~/
          paths:
            - lkpy
            - ml-100k
    
  build-py37:
    docker:
      - image: circleci/python:3.7-stretch
    <<: *dirs

    steps:
      - attach_workspace:
        at: ~/
      - restore_cache:
          keys:
          - dep-eggs-py37-{{ checksum "setup.py" }}

      - run:
          name: initialize environment
          command: |
            python3 -m venv venv
            . venv/bin/activate

      - run:
          name: build and test
          command: |
            . venv/bin/activate
            python setup.py test

      - save_cache:
          paths:
            - ./.eggs
          key: dep-eggs-py37-{{ checksum "setup.py" }}  

  build-py36:
    docker:
      - image: circleci/python:3.6-stretch
    <<: *dirs

    steps:
      - attach_workspace:
          at: ~/
      - restore_cache:
          keys:
          - dep-eggs-py36-{{ checksum "setup.py" }}

      - run:
          name: initialize environment
          command: |
            python3 -m venv venv
            . venv/bin/activate

      - run:
          name: build and test
          command: |
            . venv/bin/activate
            python setup.py test

      - save_cache:
          paths:
            - ./.eggs
          key: dep-eggs-py36-{{ checksum "setup.py" }}  

  build-py35:
    docker:
      - image: circleci/python:3.5-stretch
    <<: *dirs

    steps:
      - attach_workspace:
          at: ~/
      - restore_cache:
          keys:
          - dep-eggs-py35-{{ checksum "setup.py" }}

      - run:
          name: initialize environment
          command: |
            python3 -m venv venv
            . venv/bin/activate

      - run:
          name: build and test
          command: |
            . venv/bin/activate
            python setup.py test

      - save_cache:
          paths:
            - ./.eggs
          key: dep-eggs-py35-{{ checksum "setup.py" }}  
  
  coverage:
    docker:
      - image: circleci/python:3.7-stretch
    <<: *dirs
    steps:
      - attach_workspace:
        at: ~/

      - restore_cache:
          keys:
          - coverage-tools

      - restore_cache:
          keys:
          - dep-eggs-py37-{{ checksum "setup.py" }}
        
      - run:
          name: install deps
          command: |
            . venv/bin/activate
            pip install coverage pytest-cov invoke
      
      - run:
          name: build for coverage
          command: |
            . venv/bin/activate
            invoke build --cover
      
      - run:
          name: run test coverage
          command: |
            . venv/bin/activate
            invoke test --cover --no-eval --verbose

      - run:
          name: process coverage data
          command: |
            . venv/bin/activate
            coverage xml
            bash <(curl -s https://codecov.io/bash)

workflows:
  version: 2
  reg_build:
    jobs:
      - checkout
      - build-py37:
          requires:
            - checkout
      - build-py36:
          requires:
            - checkout
      - build-py35:
          requires:
            - checkout
