{% set data = load_setup_py_data() %}

package:
  name: lenskit
  {% if GIT_DESCRIBE_NUMBER > '0' %}
  version: {{data.get('version')}}.dev{{GIT_DESCRIBE_NUMBER}}+{{GIT_DESCRIBE_HASH}}
  {% else %}
  version: {{data.get('version')}}
  {% endif %}

source:
  path: ../

build:
  number: 0
  script: |
    # build helper library for Conda / MKL
    {{ PYTHON }} setup.py build_helper #[not osx]
    {{ PYTHON }} -m pip install --no-deps .

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python {{ python }}
    - setuptools
    - pytest-runner
    - pip
    - mkl-devel #[not osx]
  run:
    - python {{ python }}
    - pandas >=0.24
    - scipy >=1.2
    - numpy >=1.17
    - numba >=0.45,<0.52
    - pyarrow >=0.15
    - cffi >=1.12.2
    - binpickle >=0.1
    - mkl-service #[not osx]
  run_constrained:
    - scikit-learn >=0.22
    - tensorflow >=2.1

test:
  source_files:
    - pytest.ini
    - tests
    - tests/*.py
    - tests/*.csv
    - data
    - data/ml-latest-small
    - data/ml-latest-small/*.csv
  requires:
    - pytest
    - hypothesis
    - scikit-learn
  commands:
    - pytest tests -m "not slow" --verbose
