{% set data = load_setup_py_data() %}

package:
  name: lkpy
  version: {{data.get('version')}}

source:
  path: ../

requirements:
  build:
    - {{ compiler('c') }}
    - cython
  host:
    - python {{ python }}
    - setuptools
    - pytest-runner
    - cython
    - numpy
    - scipy
  run:
    - python
    - pandas
    - scipy
    - pytables

test:
  files:
    - tests
    - ml-latest-small
  requires:
    - pytest
    - pytest-arraydiff
  commands:
    - python3 -m pytest tests
