{% set data = load_setup_py_data() %}

package:
  name: lenskit
  {% if GIT_DESCRIBE_NUMBER > '0' %}
  version: {{data.get('version')}}.dev{{GIT_DESCRIBE_NUMBER}}+{{GIT_DESCRIBE_HASH}}
  {% else %}
  version: {{data.get('version')}}
  {% endif %}

source:
  path: ../

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python {{ python }}
    - setuptools
    - pytest-runner
    - pip
    - numba >=0.43
    - pandas >=0.24
    - numpy >=1.16
    - scipy >=1.2
    - pyarrow >=0.15
    - cffi >=1.12.2
    - binpickle >=0.1
    - mkl-devel
  run:
    - python
    - pandas >=0.24
    - scipy >=1.2
    - numba >=0.43
    - pyarrow >=0.15
    - cffi >=1.12.2
    - binpickle >=0.1
  run_constrained:
    - scikit-learn >=0.23
    - tensorflow >=2.1

test:
  source_files:
    - pytest.ini
    - tests
    - tests/*.py
    - tests/*.csv
    - ml-latest-small
    - ml-latest-small/*.csv
  requires:
    - pytest
    - pytest-arraydiff
    - statsmodels
    - scikit-learn
  commands:
    - pytest tests -m "not slow" --verbose
