context:
  name: lenskit
  version: 2041.0a0
  python_min: "3.11"

recipe:
  name: lenskit
  version: ${{ version }}

build:
  number: 0

outputs:
  - package:
      name: lenskit
    build:
      script:
        - python -m pip install . --no-deps -vv

    requirements:
      build:
        - ${{ compiler('rust') }}
      host:
        - python
        - pip
        - setuptools >=70
        - setuptools-scm >=8
        - setuptools-rust >=1.11,<2
      run:
        - python
        - typing-extensions >=4.12,<5
        - pyarrow >=15
        - pandas >=2.0,<3
        - numpy >=1.25,<3
        - scipy >=1.11,<2
        - pytorch >=2.4,<3
        - more-itertools >=9.0
        - threadpoolctl >=3.0
        - structlog >=23.2
        - rich >=13.5,<14
        - pyzmq >=24
        - click >=8.1,<9
        - pydantic >=2.7,<3
        - humanize >=4.2,<5
        - prettytable >=3.14,<4
        - xopen >=2.0,<3

    tests:
      - python:
          imports:
            - lenskit
            - lenskit.data
            - lenskit.als
            - lenskit.knn

  - package:
      name: lenskit-funksvd
    build:
      noarch: python
      script:
        - "true"
    requirements:
      run:
        - ${{ pin_subpackage('lenskit') }}
        - numba >=0.56
    tests:
      - python:
          imports:
            - lenskit.funksvd

  - package:
      name: lenskit-sklearn
    build:
      script:
        - "true"
    requirements:
      run:
        - ${{ pin_subpackage('lenskit') }}
        - scikit-learn >=1.2,<2
    tests:
      - python:
          imports:
            - lenskit.sklearn.svd

  - package:
      name: lenskit-implicit
    build:
      noarch: python
      script:
        - "true"
    requirements:
      run:
        - ${{ pin_subpackage('lenskit') }}
        - implicit >=0.7.2
    tests:
      - python:
          imports:
            - lenskit.implicit

  - package:
      name: lenskit-hpf
    build:
      noarch: python
      script:
        - "true"
    requirements:
      run:
        - ${{ pin_subpackage('lenskit') }}
        - hpfrec =0.2
    tests:
      - python:
          imports:
            - lenskit.hpf

about:
  license: MIT
  license_file: LICENSE.md
  summary: Recommender systems tools for Python
  description: |
    LensKit is an open-source toolkit for building, researching, and learning
    about recommender systems.

  homepage: https://lenskit.org
  repository: https://github.com/lenskit/lkpy
  documentation: https://lkpy.lenskit.org/

extra:
  recipe-maintainers:
    - mdekstrand
