name: Build Packages
on:
  push:
    branches:
      - master
    tag:
jobs:
  conda:
    name: Build Packages on ${{matrix.platform}}
    runs-on: ${{matrix.platform}}-latest
    strategy:
      fail-fast: false
      matrix:
        platform:
        - macos
        - windows
        - ubuntu

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Fetch Git tags
      run: git fetch --tags

    - name: Fix Conda Perms
      if: runner.os == 'macOS'
      run: sudo chown -R $USER $CONDA/

    - name: Set Conda path
      run: echo "::add-path::$CONDA/condabin"
      shell: bash

    - name: Install Conda deps
      run: conda install -qy conda-build

    - name: Build Conda packages
      run: conda --croot dist build conda

    - name: Clean up Conda build leftovers
      run: conda --croot dist build purge
      
    - name: Upload packages
      uses: actions/upload-artifact@v1
      with:
        name: conda-pkgs
        path: dist
