name: Build Packages
on:
  push:
    branches:
      - master
    tag:
  release:
    types: [published]
jobs:
  conda:
    name: Build Packages on ${{matrix.platform}}
    runs-on: ${{matrix.platform}}-latest
    strategy:
      fail-fast: false
      matrix:
        platform:
        - macos
        - windows
        - ubuntu
        include:
        - platform: macos
          condaplat: osx-64
        - platform: ubuntu
          condaplat: linux-64
        - platform: windows
          condaplat: win-64

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Fetch Git tags
      run: git fetch --tags

    - name: Fix Conda Perms
      if: runner.os == 'macOS'
      run: sudo chown -R $USER $CONDA/

    - name: Set Conda path
      run: echo "::add-path::$CONDA/condabin"
      shell: bash

    - name: Install Conda deps
      run: |
        conda update -qy --all
        conda install -qy conda-build

    - name: Build Conda packages
      run: |
        cd conda
        conda build -c lenskit .

    - name: Copy Conda packages
      run: |
        $ddir = (Join-Path dist ${{matrix.condaplat}})
        $bld = (Join-Path $env:CONDA conda-bld ${{matrix.condaplat}})
        New-Item -Type Directory $ddir
        Get-ChildItem $bld |Copy-Item -Destination $ddir
        Get-ChildItem -Recurse dist
      shell: pwsh
      
    - name: Upload packages
      uses: actions/upload-artifact@v1
      with:
        name: conda-pkgs
        path: dist
