name: Conda Package Tests

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: conda-test-${{github.ref}}
  cancel-in-progress: true

jobs:
  conda-build:
    name: Build Conda packages on ${{matrix.platform}}
    runs-on: ${{matrix.platform}}
    strategy:
      fail-fast: false
      matrix:
        platform:
          - ubuntu-latest
          - macos-latest
          - windows-latest

    steps:
      - name: 🛒 Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 🔬 Install Conda base
        uses: mamba-org/setup-micromamba@v2
        with:
          environment-name: build
          create-args: rattler-build uv

      - name: 🔨 Build Conda packages
        run: |
          uv run --only-group=scripting invoke build-conda
        shell: bash -el {0}

      - name: Save package
        uses: actions/upload-artifact@v4
        with:
          name: conda-pkgs-${{matrix.platform}}
          path: dist/conda
