name: Documentation
'on':
  push:
    branches:
      - main
  pull_request: {}
defaults:
  run:
    shell: bash -el {0}
concurrency:
  group: test-${{github.ref}}
  cancel-in-progress: true
jobs:
  build:
    name: Build documentation
    runs-on: ubuntu-lates
    stages:
      - name: 🛒 Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - id: setup-env
        name: 📦 Set up Conda environment
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: docs/environment.yml
          environment-name: lkpy
          init-shell: bash
      - id: install
        name: 🍱 Install LensKit packages
        run: |
          pip install --no-deps -e lenskit -e lenskit-funksvd -e lenskit-implicit
      - id: docs
        name: 📚 Build documentation site
        run: |
          just docs
      - name: 📤 Package documentation site
        uses: actions/upload-artifact@v4
        with:
          name: lenskit-docs
          path: build/doc
