name: PyPI Packages

on:
  push:
    branches:
      - main
  pull_request:
  release:
    types: [published]

jobs:
  sdist:
    name: Build sdist
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 🏷️ Fetch Git tags
        run: git fetch --tags

      - name: 🕶️ Install uv
        uses: astral-sh/setup-uv@v5
        with:
          python-version: "3.12"

      - name: Build source distribution
        run: |
          uv build --sdist

      - name: Save archive
        uses: actions/upload-artifact@v4
        with:
          name: pypi-dist-src
          path: dist

      - name: List dist dir
        run: ls -R dist

  wheels:
    name: Build wheels on ${{ matrix.os }}
    needs: [sdist]
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - ubuntu-24.04-arm
          - windows-latest
          # macos-13 is an intel runner, macos-14 is apple silicon
          - macos-13
          - macos-14

    steps:
      - name: Fetch source distribution
        uses: actions/download-artifact@v4
        with:
          name: pypi-dist-src
          path: dist

      - name: Extract source distribution
        run: |
          tar xvf dist/lenskit-*.tar.gz --strip-components=1

      - name: Build wheels
        uses: PyO3/maturin-action@v1
        with:
          args: --release --out dist

      - uses: actions/upload-artifact@v4
        with:
          name: pypi-dist-wheels-${{ matrix.os }}-${{ strategy.job-index }}
          path: ./dist/*.whl

  pypi-publish:
    name: Publish to PyPI
    runs-on: ubuntu-latest
    needs: [sdist, wheels]
    if: github.event_name == 'release'

    environment: release
    permissions:
      id-token: write

    steps:
      - name: Fetch compiled package distributions
        uses: actions/download-artifact@v4
        with:
          pattern: pypi-dist-*
          path: dist
          merge-multiple: true

      - name: List distribution artifacts
        run: ls -R dist

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
