name: Distribution

on:
  push:
    branches:
      - main
  pull_request:
  release:
    types: [published]

jobs:
  sdist:
    name: Build sdist
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Fetch Git tags
        run: git fetch --tags

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Python deps
        run: pip install -U build

      - name: Build source distribution
        run: |
          python -m build -o dist -s

      - name: Save archive
        uses: actions/upload-artifact@v4
        with:
          name: pypi-dist-src
          path: dist

      - name: List dist dir
        run: ls -R dist

  wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - ubuntu-24.04-arm
          - windows-latest
          # macos-13 is an intel runner, macos-14 is apple silicon
          - macos-13
          - macos-14

    steps:
      - uses: actions/checkout@v4

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.23.2
        with:
          output-dir: dist/wheelhouse
        env:
          MACOSX_DEPLOYMENT_TARGET: "10.12"
          CIBW_BEFORE_ALL_LINUX: curl -sSf https://sh.rustup.rs | sh -s -- -y
          CIBW_BEFORE_ALL_WINDOWS: rustup target add i686-pc-windows-msvc
          CIBW_ENVIRONMENT_LINUX: "PATH=$HOME/.cargo/bin:$PATH"

      - uses: actions/upload-artifact@v4
        with:
          name: pypi-dist-wheels-${{ matrix.os }}-${{ strategy.job-index }}
          path: ./dist/wheelhouse/*.whl

  pypi-publish:
    name: Publish to PyPI
    runs-on: ubuntu-latest
    needs: [sdist, wheels]
    if: github.event_name == 'release'

    environment: release
    permissions:
      id-token: write

    steps:
      - name: Fetch compiled package distributions
        uses: actions/download-artifact@v4
        with:
          pattern: pypi-dist-*
          path: dist

      - name: List distribution artifacts
        run: ls -R dist

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
