name: Test Suite
'on':
  push:
    branches:
    - main
  pull_request: {}
defaults:
  run:
    shell: bash -el {0}
concurrency:
  group: test-${{github.ref}}
  cancel-in-progress: true
jobs:
  conda:
    name: Conda Python ${{matrix.python}} on ${{matrix.platform}}
    runs-on: ${{matrix.platform}}
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        python:
        - '3.10'
        - '3.11'
        platform:
        - ubuntu-latest
        - macos-latest
        - windows-latest
        - macos-13
    steps:
    - name: 🛒 Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: 🐍 Set up Python
      uses: actions/setup-python@v5
      id: pyinstall
      with:
        python-version: ${{matrix.python}}
    - name: 🕶️ Set up uv
      run: |
        pip install -U 'uv>=0.1.15'
    - name: 📦 Set up Python dependencies
      id: install-deps
      run: |
        uv pip install --python $PYTHON -r test-requirements.txt -e .
      env:
        PYTHON: ${{steps.install-python.outputs.python-path}}
        UV_EXTRA_INDEX_URL: https://download.pytorch.org/whl/cpu
        UV_INDEX_STRATEGY: unsafe-first-match
    - name: 🔍 Inspect environment
      run: |
        python -V
        numba -s
    - name: 🏃🏻‍➡️ Test LKPY
      run: |
        python -m pytest --cov=lenskit --verbose --log-file=test.log --durations=25
    - name: 📐 Coverage results
      run: coverage xml
    - name: 📤 Upload test results
      uses: actions/upload-artifact@v3
      with:
        name: test-conda-${{matrix.platform}}-py${{matrix.python}}
        path: |
          test*.log
          coverage.xml
  vanilla:
    name: Vanilla Python ${{matrix.python}} on ${{matrix.platform}}
    runs-on: ${{matrix.platform}}
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        python:
        - '3.10'
        - '3.11'
        platform:
        - ubuntu-latest
        - macos-latest
        - windows-latest
    steps:
    - name: 🛒 Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: 🐍 Set up Python
      uses: actions/setup-python@v5
      id: pyinstall
      with:
        python-version: ${{matrix.python}}
    - name: 🕶️ Set up uv
      run: |
        pip install -U 'uv>=0.1.15'
    - name: 📦 Set up Python dependencies
      id: install-deps
      run: |
        uv pip install --python $PYTHON -r test-requirements.txt -e .
      env:
        PYTHON: ${{steps.install-python.outputs.python-path}}
        UV_EXTRA_INDEX_URL: https://download.pytorch.org/whl/cpu
        UV_INDEX_STRATEGY: unsafe-first-match
    - name: 🔍 Inspect environment
      run: |
        python -V
        numba -s
    - name: 🏃🏻‍➡️ Test LKPY
      run: |
        python -m pytest --cov=lenskit --verbose --log-file=test.log --durations=25
    - name: 📐 Coverage results
      run: coverage xml
    - name: 📤 Upload test results
      uses: actions/upload-artifact@v3
      with:
        name: test-vanilla-${{matrix.platform}}-py${{matrix.python}}
        path: |
          test*.log
          coverage.xml
  nojit:
    name: Non-JIT test coverage
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
    - name: 🛒 Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: 🐍 Set up Python
      uses: actions/setup-python@v5
      id: pyinstall
      with:
        python-version: '3.10'
    - name: 🕶️ Set up uv
      run: |
        pip install -U 'uv>=0.1.15'
    - name: 📦 Set up Python dependencies
      id: install-deps
      run: |
        uv pip install --python $PYTHON -r test-requirements.txt -e .
      env:
        PYTHON: ${{steps.install-python.outputs.python-path}}
        UV_EXTRA_INDEX_URL: https://download.pytorch.org/whl/cpu
        UV_INDEX_STRATEGY: unsafe-first-match
    - name: 🔍 Inspect environment
      run: |
        python -V
        numba -s
    - name: 🏃🏻‍➡️ Test LKPY
      run: |
        python -m pytest --cov=lenskit --verbose --log-file=test.log --durations=25 -m "not slow"
      env:
        NUMBA_DISABLE_JIT: 1
        PYTORCH_JIT: 0
    - name: 📐 Coverage results
      run: coverage xml
    - name: 📤 Upload test results
      uses: actions/upload-artifact@v3
      with:
        name: test-nojit
        path: |
          test*.log
          coverage.xml
  mindep:
    name: Minimal dependency tests
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
    - name: 🛒 Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: 🐍 Set up Python
      uses: actions/setup-python@v5
      id: pyinstall
      with:
        python-version: '3.10'
    - name: 🕶️ Set up uv
      run: |
        pip install -U 'uv>=0.1.15'
    - name: 📦 Set up Python dependencies
      id: install-deps
      run: |
        uv pip install --python $PYTHON -r test-requirements.txt -e . --resolution=lowest-direct
      env:
        PYTHON: ${{steps.install-python.outputs.python-path}}
        UV_EXTRA_INDEX_URL: https://download.pytorch.org/whl/cpu
        UV_INDEX_STRATEGY: unsafe-first-match
    - name: 🔍 Inspect environment
      run: |
        python -V
        numba -s
    - name: 🏃🏻‍➡️ Test LKPY
      run: |
        python -m pytest --cov=lenskit --verbose --log-file=test.log --durations=25
    - name: 📐 Coverage results
      run: coverage xml
    - name: 📤 Upload test results
      uses: actions/upload-artifact@v3
      with:
        name: test-mindep
        path: |
          test*.log
          coverage.xml
  results:
    name: Test suite results
    runs-on: ubuntu-latest
    needs:
    - conda
    - vanilla
    - nojit
    - mindep
    steps:
    - name: 🛒 Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: 📥 Download test artifacts
      uses: actions/download-artifact@v3
      with:
        path: test-logs
    - name: 📋 List log files
      run: ls -lR test-logs
    - name: ✅ Upload coverage
      uses: codecov/codecov-action@v3
      with:
        directory: test-logs/
