name: Test Suite
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  conda:
    name: Conda Python ${{matrix.python}} on ${{matrix.platform}}
    runs-on: ${{matrix.platform}}-latest
    timeout-minutes: 30
    strategy:
      matrix:
        python:
        - 3.6
        - 3.7
        - 3.8
        platform:
        - macos
        - windows
        - ubuntu
    steps:
      - uses: actions/checkout@v2
      
      - uses: ./.github/actions/conda-env
        with:
          name: lkpy
          env-file: environment.yml
          python-version: ${{matrix.python}}

      - name: Install add-on packages
        if: runner.os == 'Linux' && matrix.python == 3.8
        run: conda install -qy implicit hpfrec

      - name: Inspect environment
        run: |
          python -V
          conda info
          numba -s

      - name: Cache ML data
        uses: action/cache@v2
        with:
          path: |
            ml-100k
            data
        key: ${{runner.os}}-mldata
      
      - name: Download ML-100K
        shell: bash
        run: |
          if [ ! -r ml-100k/u.data ]; then
            wget --no-verbose -O ml-100k.zip http://files.grouplens.org/datasets/movielens/ml-100k.zip
            unzip ml-100k.zip
          fi
        
      - name: Download Other ML
        if: runner.os == 'Linux' && matrix.python == 3.8
        shell: bash
          cd data
          if [ ! -r ml-1m/ratings.dat ]; then
            wget --no-verbose -O ml-1m.zip http://files.grouplens.org/datasets/movielens/ml-1m.zip
            unzip ml-1m.zip
            rm ml-1m.zip
          fi
          if [ ! -r ml-10M100K/ratings.dat ]; then
            wget --no-verbose -O ml-10m.zip http://files.grouplens.org/datasets/movielens/ml-10m.zip
            unzip ml-10m.zip
            rm ml-10m.zip
          fi
          if [ ! -r ml-20m/ratings.csv ]; then
            wget --no-verbose -O ml-20m.zip http://files.grouplens.org/datasets/movielens/ml-20m.zip
            unzip ml-20m.zip
            rm ml-20m.zip
          fi
      
      - name: Build LKPY
        run: |
          mkdir -p build
          python setup.py build_helper || exit 2
          python setup.py build
      
      - name: Test LKPY
        run: |
          python -m pytest --cov=lenskit --verbose
        env:
          MKL_THREADING_LAYER: tbb
          NUMBA_NUM_THREADS: 4
          MKL_NUM_THREADS: 1
      
      - name: Non-JIT Test Coverage
        if: runner.os == 'Linux'
        env:
          NUMBA_DISABLE_JIT: 1
        run: |
          python -m pytest --cov=lenskit --cov-append -m 'not slow'

      - name: Aggreagate Coverage Data
        run: coverage xml

      - uses: codecov/codecov-action@v1
     
      - name: Validate Documentation Examples
        if: runner.os == 'Linux'
        run: |
          cp -r ml-100k doc
          cp -r ml-latest-small doc
          export PYTHONPATH="$PWD"
          python -m pytest --nbval-lax doc

  vanilla:
    name: Vanilla Python ${{matrix.python}} on ${{matrix.platform}}
    runs-on: ${{matrix.platform}}-latest
    strategy:
      matrix:
        python:
        - 3.6
        - 3.7
        - 3.8
        platform:
        - windows
        - ubuntu
    steps:
      - name: Check out source
        uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: ${{matrix.python}}
          architecture: x64

      - name: Set up Python deps
        env:
          PIP_PREFER_BINARY: 'true'
        run: |
          python -m pip install --upgrade pip
          python -m pip install pytest pytest-cov pytest-doctestplus
          python -m pip install -e .

      - name: Run tests
        run: |
          python -m pytest --cov=lenskit --cov-report=xml
      
      - name: Upload coverage
        uses: codecov/codecov-action@v1

  mindep:
    name: Minimal Supported Dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Check out source
        uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.6'
          architecture: x64

      - name: Set up Python deps
        run: |
          python -m pip install --upgrade pip
          python -m pip install pytest pytest-cov pytest-doctestplus
          python -m pip install -c min-constraints.txt -e .

      - name: Run tests
        run: |
          python -m pytest --cov=lenskit --cov-report=xml
        
      - name: Upload coverage
        uses: codecov/codecov-action@v1
